@BASE_URL=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM5NDcxYjgzZGJhN2FjNDNiNThiYWQiLCJpYXQiOjE3NjU5NTM5MTcsImV4cCI6MTc2NjA0MDMxN30.KQk7B_FoqQzulZKcskC-w8HTE9mb0yLngtNP-EYgGlI

### create new user
POST {{BASE_URL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "henryer Doe",
    "email": "henryeer.doe@gmail.com",
    "password": "password"
}

### Get all users
GET {{BASE_URL}}/users 
 
### Get user by id

GET {{BASE_URL}}/users/691af6ce679594af902955ef

### Update user by id
PATCH {{BASE_URL}}/users/691b00adc7abc32e2e5f4044
Content-Type: application/json

{
    "email": "jack.doe@example.com"
}

### Delete user by id
DELETE {{BASE_URL}}/users/691b00adc7abc32e2e5f4044

### Register a new user
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name":"henry Doe",
    "email":"henry.doe@gmail.com",
    "password":"password"
}

### Login a user
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email":"henry.doe@gmail.com",
    "password":"password"
}

### Create a new Trip
POST {{BASE_URL}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
   
    "title": "Trip to Kathmandu",
    "description": "A fun trip with friends",
    "startDate": "2025-12-20",
    "endDate": "2025-12-25",
    "destinations": ["Pashupatinath", "Swayambhu"],
    "budget": {
        "total": 50000,
        "spent": 0,
        "expenses": [
            {
                "name": "Hotel",
                "amount": 10000,
                "date": "2025-12-20"
            },
            {
                "name": "Food",
                "amount": 22000,
                "date": "2025-12-21"
            }
        ]
    }
}

### Get all Trips
GET {{BASE_URL}}/trips
Authorization: Bearer {{token}}

### Get Trip by id
GET {{BASE_URL}}/trips/693a984f01bfc1e2a3cf722f
Authorization: Bearer {{token}}


### Update Trip by id
PATCH {{BASE_URL}}/trips/693a984f01bfc1e2a3cf722f
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Trip to Pokhara and Lakeeside",
     "budget": {
    "total": 50000,
    "spent": 32000,
    "expenses": [
      {
        "name": "drinks",
        "amount": 28000,
        "date":"2025-12-22"
      }]
}}

### Delete Trip by id
DELETE {{BASE_URL}}/trips/693910e6cdb7caf7e1c10af6
