@BASE_URL=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTRiOWMzZjE1NDFhY2QyNTVjMWJhMDQiLCJpYXQiOjE3NjY1NjI4NzksImV4cCI6MTc2NjY0OTI3OX0.JJomN1zlasgFb5n88FS9MSzDI1zz8jSLvQyU8GU_qSg
### create new user
POST {{BASE_URL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "henryer Doe",
    "email": "henr.doe@gmail.com",
    "password": "password"
}

### Get all users
GET {{BASE_URL}}/users?search=jo&sort=id&order=asc
Authorization: Bearer {{token}}
 
### Get user by id

GET {{BASE_URL}}/users/691af6ce679594af902955ef
Authorization: Bearer {{token}}

### Update user by id
PATCH {{BASE_URL}}/users/691b00adc7abc32e2e5f4044
Content-Type: application/json

{
    "email": "jack.doe@example.com"
}

### Delete user by id
DELETE {{BASE_URL}}/users/691b00adc7abc32e2e5f4044

### Register a new user
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name":"Bijita Bhattarai",
    "email":"bbb@gmail.com",
    "password":"bijitabhat"
}

### Login a user
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email":"bijita@gmail.com",
    "password":"bijitabhat"
}

### Create a new Trip
POST {{BASE_URL}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
   
    "title": "Trip to Kathmandu",
    "description": "A fun trip with friends",
    "startDate": "2025-12-20",
    "endDate": "2025-12-25",
    "destinations": ["Pashupatinath", "Swayambhu"],
    "budget": {
        "total": 50000,
        "spent": 0,
        "expenses": [
            {
                "name": "Hotel",
                "amount": 10000,
                "date": "2025-12-20"
            },
            {
                "name": "Food",
                "amount": 22000,
                "date": "2025-12-21"
            }
        ]
    }
}

### Get all Trips
GET {{BASE_URL}}/trips
Authorization: Bearer {{token}}

### Get Trip by id
GET {{BASE_URL}}/trips/693a984f01bfc1e2a3cf722f
Authorization: Bearer {{token}}


### Update Trip by id
PATCH {{BASE_URL}}/trips/693a984f01bfc1e2a3cf722f
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Trip to Pokhara and Lakeeside",
     "budget": {
    "total": 50000,
    "spent": 32000,
    "expenses": [
      {
        "name": "drinks",
        "amount": 28000,
        "date":"2025-12-22"
      }]
}}

### Delete Trip by id
DELETE {{BASE_URL}}/trips/693910e6cdb7caf7e1c10af6

### create a new baggage
POST {{BASE_URL}}/693a984f01bfc1e2a3cf722f/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "jacket"
}

### get all baggages
GET {{BASE_URL}}/693a984f01bfc1e2a3cf722f/baggages
Authorization: Bearer {{token}}

### get baggages by id
GET {{BASE_URL}}/693a984f01bfc1e2a3cf722f/baggages/694530be76254d99e5bd7718
Authorization: Bearer {{token}}

### update baggae by id
PATCH {{BASE_URL}}/693a984f01bfc1e2a3cf722f/baggages/69452fa976254d99e5bd770b
Content-Type: application/json
Authorization: Bearer {{token}}

{
     "name": "Sweater",
  "completed": true
}

### delete baggage by id
DELETE {{BASE_URL}}/693a984f01bfc1e2a3cf722f/baggages/69452f9376254d99e5bd7707
Authorization: Bearer {{token}}


### Invite collaborators to a trip
POST {{BASE_URL}}/trips/693a984f01bfc1e2a3cf722f/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "collaboratorEmails": [
    "bhattaraibijita103@gmail.com",
    "bijitabhattarai242@gmail.com"
  ]
}


